import argparse
import json
import re
import time
import unicodedata
from difflib import SequenceMatcher
from pathlib import Path

import pandas as pd
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from src.data.enrichment_store import (
    load_enrichment,
    save_enrichment,
)
from src.data.fetch_player_profiles import zodiac_from_date


# ---------------------------------------------------------
# PATHS
# ---------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

REFERENCE_DIR = (
    PROJECT_ROOT
    / "data"
    / "reference"
)

PLAYERS_PATH = (
    REFERENCE_DIR
    / "players.csv"
)

LOOKUP_LOG_PATH = (
    REFERENCE_DIR
    / "wikidata_lookup_log.csv"
)

RAW_DIR = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "wikidata"
)

RAW_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ---------------------------------------------------------
# WIKIDATA CONFIGURATION
# ---------------------------------------------------------

WIKIDATA_API = (
    "https://www.wikidata.org/w/api.php"
)

FOOTBALL_TERMS = [
    "footballer",
    "football player",
    "association football",
    "soccer player",
    "professional football",
]


def create_session():

    session = requests.Session()

    retries = Retry(
        total=5,
        backoff_factor=1.0,
        status_forcelist=[
            429,
            500,
            502,
            503,
            504,
        ],
        allowed_methods=["GET"],
    )

    adapter = HTTPAdapter(
        max_retries=retries
    )

    session.mount(
        "https://",
        adapter,
    )

    session.headers.update(
        {
            "User-Agent":
                "EPL-Zodiac-Thesis/1.0 "
                "(University research project)"
        }
    )

    return session


SESSION = create_session()


# ---------------------------------------------------------
# CACHE
# ---------------------------------------------------------

def cache_path(player_id):

    return (
        RAW_DIR
        / f"player_{int(player_id)}.json"
    )


def load_cache(player_id):

    path = cache_path(
        player_id
    )

    if not path.exists():
        return None

    try:

        with open(
            path,
            "r",
            encoding="utf-8",
        ) as file:

            payload = json.load(
                file
            )

        # Only use cache generated by
        # this version of the script.
        if (
            isinstance(payload, dict)
            and payload.get(
                "cache_version"
            ) == 2
        ):
            return payload

    except Exception:
        pass

    return None


def save_cache(
    player_id,
    payload,
):

    path = cache_path(
        player_id
    )

    payload[
        "cache_version"
    ] = 2

    with open(
        path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            payload,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ---------------------------------------------------------
# NAME NORMALISATION
# ---------------------------------------------------------

def normalise_name(value):

    if value is None:
        return ""

    value = str(value)

    value = unicodedata.normalize(
        "NFKD",
        value,
    )

    value = "".join(
        char
        for char in value
        if not unicodedata.combining(
            char
        )
    )

    value = value.lower()

    value = re.sub(
        r"[^a-z0-9 ]+",
        " ",
        value,
    )

    value = re.sub(
        r"\s+",
        " ",
        value,
    )

    return value.strip()


def name_similarity(
    player_name,
    candidate_name,
):

    player = normalise_name(
        player_name
    )

    candidate = normalise_name(
        candidate_name
    )

    if not player or not candidate:
        return 0

    if player == candidate:
        return 100

    player_tokens = (
        player.split()
    )

    candidate_tokens = (
        candidate.split()
    )

    # Useful for names where Wikidata
    # contains an additional middle name.
    if (
        len(player_tokens) >= 2
        and all(
            token in candidate_tokens
            for token in player_tokens
        )
    ):
        return 94

    score = SequenceMatcher(
        None,
        player,
        candidate,
    ).ratio()

    return round(
        score * 100,
        2,
    )


# ---------------------------------------------------------
# WIKIDATA REQUESTS
# ---------------------------------------------------------

def wikidata_request(params):

    response = SESSION.get(
        WIKIDATA_API,
        params=params,
        timeout=30,
    )

    response.raise_for_status()

    return response.json()


def search_wikidata(
    player_name,
):

    params = {
        "action":
            "wbsearchentities",

        "format":
            "json",

        "language":
            "en",

        "uselang":
            "en",

        "type":
            "item",

        "limit":
            10,

        "search":
            player_name,
    }

    return wikidata_request(
        params
    )


def fetch_entity(qid):

    params = {
        "action":
            "wbgetentities",

        "format":
            "json",

        "ids":
            qid,

        "props":
            "claims|labels|descriptions",

        "languages":
            "en",
    }

    return wikidata_request(
        params
    )


# ---------------------------------------------------------
# FOOTBALL CANDIDATES
# ---------------------------------------------------------

def is_football_candidate(
    result,
):

    description = (
        result.get(
            "description"
        )
        or ""
    ).lower()

    return any(
        term in description
        for term in FOOTBALL_TERMS
    )


def choose_candidate(
    player_name,
    search_payload,
):

    # Single-name players are too risky
    # for automatic Wikidata matching.
    if len(
        normalise_name(
            player_name
        ).split()
    ) == 1:

        return (
            None,
            "single_name_manual_review",
            [],
        )

    search_results = (
        search_payload.get(
            "search",
            []
        )
    )

    candidates = []

    for result in search_results:

        if not is_football_candidate(
            result
        ):
            continue

        label = result.get(
            "label",
            ""
        )

        score = name_similarity(
            player_name,
            label,
        )

        candidates.append(
            {
                "qid":
                    result.get("id"),

                "label":
                    label,

                "description":
                    result.get(
                        "description"
                    ),

                "score":
                    score,
            }
        )

    candidates = sorted(
        candidates,
        key=lambda item:
            item["score"],
        reverse=True,
    )

    if not candidates:

        return (
            None,
            "no_confident_football_candidate",
            candidates,
        )

    best = candidates[0]

    # Minimum acceptable similarity.
    if best["score"] < 90:

        return (
            None,
            "no_confident_football_candidate",
            candidates,
        )

    # If multiple football candidates
    # exist, demand a very strong winner.
    if len(candidates) > 1:

        second = candidates[1]

        margin = (
            best["score"]
            - second["score"]
        )

        if (
            best["score"] < 95
            or margin < 8
        ):

            return (
                None,
                "ambiguous_candidates",
                candidates,
            )

    return (
        best,
        "candidate_selected",
        candidates,
    )


# ---------------------------------------------------------
# BIRTH DATE EXTRACTION
# ---------------------------------------------------------

def extract_birth_date(
    entity_payload,
    qid,
):

    entities = entity_payload.get(
        "entities",
        {}
    )

    entity = entities.get(
        qid,
        {}
    )

    claims = entity.get(
        "claims",
        {}
    )

    birth_claims = claims.get(
        "P569",
        []
    )

    if not birth_claims:
        return (
            None,
            "no_birth_date",
        )

    for claim in birth_claims:

        mainsnak = claim.get(
            "mainsnak",
            {}
        )

        datavalue = mainsnak.get(
            "datavalue",
            {}
        )

        value = datavalue.get(
            "value"
        )

        if not isinstance(
            value,
            dict,
        ):
            continue

        precision = value.get(
            "precision"
        )

        # Wikidata precision:
        # 11 = exact day
        if (
            precision is None
            or precision < 11
        ):
            continue

        time_value = value.get(
            "time"
        )

        if not time_value:
            continue

        # Example:
        # +1995-09-24T00:00:00Z
        match = re.match(
            r"^[+-](\d{4})-(\d{2})-(\d{2})T",
            time_value,
        )

        if not match:
            continue

        year, month, day = (
            match.groups()
        )

        birth_date = (
            f"{year}-"
            f"{month}-"
            f"{day}"
        )

        return (
            birth_date,
            "matched",
        )

    return (
        None,
        "insufficient_date_precision",
    )


# ---------------------------------------------------------
# LOOKUP LOG
# ---------------------------------------------------------

def save_log(results):

    if not results:
        return

    new_df = pd.DataFrame(
        results
    )

    if LOOKUP_LOG_PATH.exists():

        old_df = pd.read_csv(
            LOOKUP_LOG_PATH
        )

        combined = pd.concat(
            [
                old_df,
                new_df,
            ],
            ignore_index=True,
        )

        combined = (
            combined
            .drop_duplicates(
                subset=[
                    "player_id"
                ],
                keep="last",
            )
        )

    else:

        combined = new_df

    combined = combined.sort_values(
        "player_id"
    )

    combined.to_csv(
        LOOKUP_LOG_PATH,
        index=False,
        encoding="utf-8",
    )


# ---------------------------------------------------------
# UPDATE ENRICHMENT
# ---------------------------------------------------------

def update_enrichment(
    enrichment,
    player_id,
    birth_date,
    qid,
):

    matching_rows = enrichment[
        enrichment["player_id"]
        == int(player_id)
    ].index

    if len(matching_rows) != 1:
        return False

    index = matching_rows[0]

    # Never overwrite an existing DOB.
    if pd.notna(
        enrichment.at[
            index,
            "birth_date"
        ]
    ):
        return False

    enrichment.at[
        index,
        "birth_date"
    ] = birth_date

    enrichment.at[
        index,
        "zodiac"
    ] = zodiac_from_date(
        birth_date
    )

    enrichment.at[
        index,
        "dob_source"
    ] = f"Wikidata:{qid}"

    # Automatically matched,
    # therefore not independently verified.
    enrichment.at[
        index,
        "dob_verified"
    ] = False

    return True


# ---------------------------------------------------------
# PROCESS PLAYER
# ---------------------------------------------------------

def process_player(
    player_id,
    player_name,
):

    cached = load_cache(
        player_id
    )

    if cached is not None:

        search_payload = cached.get(
            "search_payload",
            {}
        )

    else:

        search_payload = (
            search_wikidata(
                player_name
            )
        )

        cached = {
            "player_id":
                int(player_id),

            "player_name":
                player_name,

            "search_payload":
                search_payload,
        }

        save_cache(
            player_id,
            cached,
        )

        # Be polite to Wikidata.
        time.sleep(0.25)

    candidate, status, candidates = (
        choose_candidate(
            player_name,
            search_payload,
        )
    )

    if candidate is None:

        return {
            "status":
                status,

            "qid":
                None,

            "candidate_label":
                None,

            "similarity":
                None,

            "birth_date":
                None,

            "candidates":
                candidates,
        }

    qid = candidate[
        "qid"
    ]

    # -----------------------------------------------------
    # ENTITY DATA
    # -----------------------------------------------------

    entity_payload = cached.get(
        "entity_payload"
    )

    cached_qid = cached.get(
        "entity_qid"
    )

    if (
        entity_payload is None
        or cached_qid != qid
    ):

        entity_payload = fetch_entity(
            qid
        )

        cached[
            "entity_qid"
        ] = qid

        cached[
            "entity_payload"
        ] = entity_payload

        save_cache(
            player_id,
            cached,
        )

        time.sleep(0.25)

    birth_date, birth_status = (
        extract_birth_date(
            entity_payload,
            qid,
        )
    )

    return {
        "status":
            birth_status,

        "qid":
            qid,

        "candidate_label":
            candidate["label"],

        "similarity":
            candidate["score"],

        "birth_date":
            birth_date,

        "candidates":
            candidates,
    }


# ---------------------------------------------------------
# MAIN LOOKUP
# ---------------------------------------------------------

def fill_missing_dobs(
    limit,
):

    # Generated player information.
    players = pd.read_csv(
        PLAYERS_PATH
    )

    # Persistent DOB/zodiac database.
    enrichment = load_enrichment()

    missing_ids = set(
        enrichment[
            enrichment["birth_date"].isna()
        ]["player_id"]
    )

    missing = players[
        players["player_id"].isin(
            missing_ids
        )
    ].copy()

    # -----------------------------------------------------
    # PRIORITISE PLAYERS
    # -----------------------------------------------------

    # Players never previously attempted should come
    # before old unresolved cases.
    previously_attempted = set()

    if LOOKUP_LOG_PATH.exists():

        old_log = pd.read_csv(
            LOOKUP_LOG_PATH
        )

        previously_attempted = set(
            old_log[
                "player_id"
            ].dropna().astype(int)
        )

    missing[
        "previously_attempted"
    ] = missing[
        "player_id"
    ].isin(
        previously_attempted
    )

    missing = missing.sort_values(
        [
            "previously_attempted",
            "appearances",
        ],
        ascending=[
            True,
            False,
        ],
    )

    if limit is not None:
        missing = missing.head(
            limit
        )

    print(
        f"Players currently missing DOB: "
        f"{len(missing_ids)}"
    )

    print(
        f"Players selected this run: "
        f"{len(missing)}"
    )

    results = []

    matched_count = 0

    # -----------------------------------------------------
    # LOOKUPS
    # -----------------------------------------------------

    for number, (
        _,
        row,
    ) in enumerate(
        missing.iterrows(),
        start=1,
    ):

        player_id = int(
            row["player_id"]
        )

        player_name = row[
            "player_name"
        ]

        print(
            f"[{number}/{len(missing)}] "
            f"{player_name} "
            f"(ID {player_id})"
        )

        try:

            result = process_player(
                player_id,
                player_name,
            )

            status = result[
                "status"
            ]

            print(
                f"    -> {status}"
            )

            if status == "matched":

                updated = (
                    update_enrichment(
                        enrichment,
                        player_id,
                        result[
                            "birth_date"
                        ],
                        result[
                            "qid"
                        ],
                    )
                )

                if updated:

                    matched_count += 1

                    print(
                        f"       "
                        f"{result['birth_date']} "
                        f"({result['qid']})"
                    )

            results.append(
                {
                    "player_id":
                        player_id,

                    "player_name":
                        player_name,

                    "status":
                        status,

                    "qid":
                        result["qid"],

                    "candidate_label":
                        result[
                            "candidate_label"
                        ],

                    "similarity":
                        result[
                            "similarity"
                        ],

                    "birth_date":
                        result[
                            "birth_date"
                        ],
                }
            )

        except Exception as exc:

            print(
                f"    -> error: {exc}"
            )

            results.append(
                {
                    "player_id":
                        player_id,

                    "player_name":
                        player_name,

                    "status":
                        "error",

                    "qid":
                        None,

                    "candidate_label":
                        None,

                    "similarity":
                        None,

                    "birth_date":
                        None,
                }
            )

    # -----------------------------------------------------
    # SAVE
    # -----------------------------------------------------

    save_enrichment(
        enrichment
    )

    save_log(
        results
    )

    # -----------------------------------------------------
    # SUMMARY
    # -----------------------------------------------------

    total = len(
        enrichment
    )

    with_dob = (
        enrichment[
            "birth_date"
        ]
        .notna()
        .sum()
    )

    print("\n==============================")
    print("WIKIDATA LOOKUP SUMMARY")
    print("==============================")

    if results:

        result_df = pd.DataFrame(
            results
        )

        print(
            result_df[
                "status"
            ]
            .value_counts(
                dropna=False
            )
            .to_string()
        )

        print()

    print(
        f"New DOBs added: "
        f"{matched_count}"
    )

    print(
        f"Total DOB coverage: "
        f"{with_dob}/{total}"
    )

    print(
        f"Still missing: "
        f"{total - with_dob}"
    )

    print("==============================\n")


# ---------------------------------------------------------
# CLI
# ---------------------------------------------------------

def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--limit",
        type=int,
        default=25,
        help=(
            "Maximum number of missing players "
            "to attempt in this run."
        ),
    )

    args = parser.parse_args()

    fill_missing_dobs(
        limit=args.limit
    )


if __name__ == "__main__":
    main()